version: "3.9"

services:
  user:
    container_name: user-service
    build: ./services/user-service
    image: local/user:dev
    ports:
      - "3001:3001" # host:container
    env_file:
      - ./services/user-service/.env
    restart: unless-stopped
